version: '3'

services:
  mongo:
    image: mongo:latest
    ports:
        - "27017:27017"
    container_name: mongo_container
    restart: always
    environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: admin
        MONGO_INITDB_DATABASE: blognextjs